# 👾 The Alien Invasion!

**Scenario:**

You're a data analyst at the Earth Defence Organisation (EDO). You've just received a transmission containing **data about an alien fleet** heading towards Earth! The transmission contains vital data about each alien spaceship's **dimensions, speed, and weapon power**. Your job is to analyze this data to provide the EDO with the insights needed to prepare Earth's defenses. 

**Exercise:**

The transmission is an matrix (an array) which contains data for each spaceship. Every line represents one spaceship, with values in the order of: **length** (in meters), **width** (in meters), **height** (in meters), **speed** (in km/s), and **weapon power** (on a scale of 1-10).

In [2]:
import numpy as np


fleet_data = np.array([
    [120, 40, 25, 2.5, 10],
    [85, 60, 30, 5.0, 5],
    [100, 50, 35, 4.5, 7],
    [120, 40, 25, 2.5, 9],
    [150, 50, 30, 3.0, 10],
], dtype=np.float32)

**Your tasks:**

1. Calculate and print the total number of spaceships.

In [5]:
fleet_length = fleet_data.shape[0]
f"Number of ships in the fleet: {fleet_length}"

'Number of ships in the fleet: 5'

2. Calculate and print the average spaceship size (volume). 

In [11]:
ships_lengths = fleet_data[:, 0]
ships_widths = fleet_data[:, 1]
ships_heights = fleet_data[:, 2]

print(f"Lengths: {ships_lengths}")
print(f"Widths: {ships_widths}")
print(f"Heights: {ships_heights}")


Lengths: [120.  85. 100. 120. 150.]
Widths: [40. 60. 50. 40. 50.]
Heights: [25. 30. 35. 25. 30.]


In [16]:
ships_volumes = ships_heights * ships_widths * ships_lengths
ships_volumes

array([120000., 153000., 175000., 120000., 225000.], dtype=float32)

3. Identify and print the speed of the fastest spaceship.

In [24]:
ships_speed = fleet_data[:,3]

max_speed = ships_speed.max()
ship_max_speed = np.argmax(ships_speed)
f"The fastest ship ({ship_max_speed}) travels at {max_speed} km/s"


'The fastest ship (1) travels at 5.0 km/s'

In [ ]:
np.argmax()

4. Determine and print the number of spaceships with the maximum weapon power.

In [26]:
ships_power = fleet_data[:, -1]
ships_with_max_power_mask = ships_power == 10
n_ships_max_power = ships_with_max_power_mask.sum()

f"The number of ships with max power is {n_ships_max_power}"

'The number of ships with max power is 2'

In [ ]:
np.array()

5. Find and print the mean speed of spaceships with the maximum weapon power.

In [28]:
ships_speed, ships_with_max_power_mask

(array([2.5, 5. , 4.5, 2.5, 3. ], dtype=float32),
 array([ True, False, False, False,  True]))

In [31]:
ships_speed[ships_with_max_power_mask].mean()

2.75

Remember, the fate of Earth depends on your quick and accurate analysis. Good luck! 🍀